CREATE TABLE gold.vbi003004 (
    `cd_hansya` STRING,
    `cd_kaisya` STRING,
    `cd_tenpo` STRING,
    `no_yoyakuid` STRING,
    `cd_yoykmsai` STRING,
    `no_msaiedmx` STRING,
    `no_stall` STRING,
    `mj_stallno` STRING,
    `mj_gyme` STRING,
    `kb_koutei` STRING,
    `dt_siyost` STRING,
    `dd_nyuukoyt` STRING,
    `tm_nyuukoytsecond` STRING,
    `dt_siyoed` STRING,
    `dd_shukkoyt` STRING,
    `tm_shukkoytsecond` STRING,
    `tm_siyotime` STRING,
    `kb_nyuuko` STRING,
    `cd_jisekist` STRING,
    `cd_restcros` STRING,
    `su_sgyninz` STRING,
    `dt_nyukjisk` STRING,
    `dt_sesnjisk` STRING,
    `mj_sakujyo` STRING
) USING PARQUET
;
