CREATE TABLE gold.vbi021002 (
`cd_hansya` STRING,
    `kj_kaisyatn` STRING,
    `cd_hanbaitn` STRING,
    `cd_kaisya` STRING,
    `kj_tenpomei` STRING,
    `NO_SYADAIBA` STRING,
    `NO_SYADAIBA_yotei` STRING,
    `MJ_KATASIKI` STRING,
    `KJ_SITAMEIG` STRING,
    `MJ_FURUSYAM` STRING,
    `KB_SIREHANB` STRING,
    `DD_KEIRIKEI_zako` STRING,
    `NO_SYADAIBA_zako` STRING,
    `MJ_KATASIKI_zako` STRING,
    `KJ_SITAMEIG_zako` STRING,
    `MJ_FURUSYAM_zako` STRING,
    `KB_SIIRE_zako` STRING,
    `DD_SIREJYTY_zako` STRING,
    `DD_SIRETORO_zako` STRING,
    `CD_SYOYUSYA_zako` STRING,
    `KJ_SAISSYYU_zako` STRING,
    `NO_SYADAIBA_shinsya` STRING,
    `kj_meigime1_shinsya` STRING,
    `dd_jucyu_shinsya` STRING,
    `dd_touroku_shinsya` STRING,
    `mj_katasiki_shinsya` STRING,
    `no_cyumon_shinsya` STRING,
    `kj_kurumame_shinsya` STRING,
    `DD_1JTOROKU` STRING
) USING PARQUET
;
