CREATE TABLE gold.vbi016011 (
    `販社コード` STRING,
    `会社コード` STRING,
    `店舗コード` STRING,
    `ソート順` STRING,
    `車名ソート順` STRING,
    `店舗短縮名称` STRING,
    `ゾーンコード` STRING,
    `ゾーン名称` STRING,
    `注文ＮＯ` STRING,
    `新車車名` STRING,
    `受注計上日` STRING,
    `グレード` STRING,
    `品名カナ` STRING,
    `法人個人区分` STRING,
    `年齢別` STRING,
    `商談動機` STRING,
    `購入形態` STRING,
    `下取有無` STRING,
    `メーカー区分` STRING,
    `下取車名` STRING,
    `車種分類` STRING,
    `下取車年式` STRING,
    `下取車メーカー` STRING
) USING PARQUET
;
