CREATE TABLE gold.vbi999002 (
    `No.` STRING,
    `販社コード` STRING,
    `会社コード` STRING,
    `店舗コード` STRING,
    `店舗名` STRING,
    `開店時間` STRING,
    `閉店時間` STRING,
    `新車受注` STRING,
    `新車販売` STRING,
    `中古車受注` STRING,
    `中古車販売` STRING,
    `表示可否1` STRING,
    `表示可否2` STRING,
    `表示可否3` STRING,
    `表示可否4` STRING,
    `表示可否5` STRING,
    `表示可否6` STRING,
    `表示可否7` STRING,
    `表示可否8` STRING,
    `表示可否9` STRING,
    `表示可否10` STRING,
    `表示可否11` STRING,
    `表示順1` STRING,
    `表示順2` STRING,
    `表示順3` STRING,
    `表示順4` STRING,
    `表示順5` STRING,
    `表示順6` STRING,
    `表示順7` STRING,
    `表示順8` STRING,
    `表示順9` STRING,
    `表示順10` STRING,
    `表示順11` STRING
) USING PARQUET
;
