CREATE TABLE gold.vbi022004 (
    `販社コード` STRING,
    `会社コード` STRING,
    `店舗コード` STRING,
    `車名` STRING,
    `店舗名称` STRING,
    `店舗短縮名称` STRING,
    `ゾーンコード` STRING,
    `ゾーン名称` STRING,
    `中古車受注実績` STRING,
    `中古車受注取消` STRING,
    `中古車受注合計` STRING,
    `中古車受注残` STRING,
    `中古車販売実績` STRING,
    `中古車販売取消` STRING,
    `中古車販売合計` STRING,
    `当月中古車販売` STRING,
    `中古車販売見込み` STRING,
    `受注日付` STRING,
    `中古車販売日付` STRING,
    `中古車見込み日付` STRING,
    `店舗ソート順` STRING,
    `車名ソート順` STRING
) USING PARQUET;
