CREATE TABLE gold.vbi013006 (
    `PK_販社会社注文NO枝番` STRING,
    `PK_販社会社店舗コード` STRING,
    `販社コード` STRING,
    `会社コード` STRING,
    `アラート判断` STRING,
    `注文no` STRING,
    `店舗コード` STRING,
    `納車日` STRING,
    `登録日` STRING,
    `受注日` STRING,
    `flg_1` STRING,
    `flg_2` STRING,
    `flg_3` STRING,
    `flg_4` STRING,
    `flg_5` STRING,
    `flg_6` STRING,
    `flg_a` STRING,
    `flg_b` STRING,
    `flg_c` STRING,
    `flg_d` STRING,
    `flg_e` STRING,
    `flg_f` STRING,
    `flg` STRING,
    `見直し回収予定日` STRING,
    `回収予定日` STRING,
    `未納車経過日` STRING,
    `登録経過日` STRING,
    `受注経過日` STRING
) USING PARQUET
;
